// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rceixowecqpiotophyku.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJjZWl4b3dlY3FwaW90b3BoeWt1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI4MDA4NDUsImV4cCI6MjA2ODM3Njg0NX0.uJvei75p_PNJDfZKcd2RB4kHIIAcUVDbeWyCPG-8fL8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});